@startuml Diagrama
class Usuario
class Mascota{
    -Felicidad felicidad
    + Pasear()
}
class Juego{
    -Mascota mascota
    - Usuario usuario 
}
class Felicidad
class Porcentaje{
    -Numero numero
    + Incrementar(int Numero)
    + Disminuir(Numero)
};

Usuario o-- Mascota
Mascota *-- Felicidad
Juego *-- Usuario
Juego *-- Mascota
Felicidad --|> Porcentaje
Porcentaje *-- Numero
@enduml